server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

spring:
  config:
    import: optional:configserver:http://localhost:8089
  application:
    name: logging-service