server:
  port: 8081

api:
  services:
    logging-service-name: logging-service
    messages-service-name: messages-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true

spring:
  application:
    name: facade-service
  cloud:
    stream:
      bindings:
        messages-out-0:
          producer:
            partition-count: 10
            partition-key-expression: headers['partitionKey']
          destination: messages
          content-type: text/plain
          group: messages_group
      kafka:
        default:
          producer:
            sync: true
        binder:
          autoAddPartitions: true
          brokers: localhost:9093